### PR TITLE
Use macos-14 runner, update dependencies

### PR DESCRIPTION
**Pull request by giarc3**

### CODE REVIEW

**Comment by leeroy-travis** [comment]
Commit SHA:30bf3cbb4312f748b0159699f72e90f3fa636173
No changes to code coverage between the base branch and the head branch

**Comment by leeroy-travis** [comment]
Commit SHA:30bf3cbb4312f748b0159699f72e90f3fa636173
No changes to code coverage between the base branch and the head branch

**Review by BobWall23 — APPROVED** [review]

**Comment by leeroy-travis** [comment]
Commit SHA:e5bc640ba3228aad6bb84ea057c5f59db5dd834b
No changes to code coverage between the base branch and the head branch

**Comment by leeroy-travis** [comment]
Commit SHA:e5bc640ba3228aad6bb84ea057c5f59db5dd834b
No changes to code coverage between the base branch and the head branch

**Review by coltfred — APPROVED** [review]

**Review by cjyar — APPROVED** [review]

**Pull request merged**
