### PR TITLE
Add Link Time Optimization flag to Rust build and turn off debug symbols

### PR DESCRIPTION
**Pull request by ernieturner**

### CODE REVIEW

**Comment by ernieturner** [comment]
@clintfred The `lto` stuff isn't supposed to make the resulting binary smaller, it's supposed to make it faster. Are you saying you're still seeing debug symbols in the resulting file?

**Comment by clintfred** [comment]
If `file` is to be believed, yes
```
$ file native/index.node 
native/index.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=71863004cf93d4a6d337fbd847d34f676e8757dc, with debug_info, not stripped
```

**Comment by clintfred** [comment]
Do you get that without these config changes as well?

**Comment by ernieturner** [comment]
I do, yes. The `file` output and the file size are the same before and after these changes.

**Comment by ernieturner** [comment]
Did some more testing on this and found out a few things

+ OSX is doing some amount of dynamic linking for it's binaries, which is why it has the reduced file size from linux
+ The underlying command that Neon runs when you run `neon build` is `cargo build` on Linux, but on OSX it's `cargo rustc --release -- -C link-args=-Wl,-undefined,dynamic_lookup`. This ends up producing either a `.so` file (Linux) or a `.dylib` file (OSX) which Neon just moves to the `index.node` file we all know and love.

**Pull request merged**
