### PR TITLE
Switch to reusable workflow

### PR DESCRIPTION
**Pull request by giarc3**

### CODE REVIEW

**Comment by leeroy-travis** [comment]
Commit SHA:39773d5d2ac3919ed1cbf69b24afe7095d6f7cbd
No changes to code coverage between the base branch and the head branch

**Comment by leeroy-travis** [comment]
Commit SHA:39773d5d2ac3919ed1cbf69b24afe7095d6f7cbd
No changes to code coverage between the base branch and the head branch

**Comment by leeroy-travis** [comment]
Commit SHA:0c6d4301aeef02a1987cdb228a171fa83a78c63a
No changes to code coverage between the base branch and the head branch

**Comment by leeroy-travis** [comment]
Commit SHA:0c6d4301aeef02a1987cdb228a171fa83a78c63a
No changes to code coverage between the base branch and the head branch

**Review by cjyar — APPROVED** [review]

**Pull request merged**
